### PR TITLE
Use the new crypto api on windows

### PR DESCRIPTION
**Pull request by feliwir**
As i was using LibreSSL for a WindowsStore project i noticed that the old Wincrypt API is not accesible anymore (it's also marked as deprecated on MSDN). The correct behaviour now is to use the new **Cryptography API: Next Generation**:
https://docs.microsoft.com/en-us/windows/win32/seccng/cng-portal

It is available from Windows Vista and onwards and should be fine for us to use.

### CODE REVIEW

**Comment by kinichiro** [comment]
PR should not post here, since this tree is copy of upstream and rebased often, as stated on top page.
And I think this topic is suitable for portable repo, rather than here.
How about close this PR and posting this topic as issue on https://github.com/libressl-portable/portable/issues with your diff ?

**Comment by feliwir** [comment]
I am not used to creating patch files or diff files of any sort, since that's not how i usually work. I can move the issue over to the portable project, but i'd be happy if someone else creates the diff.

**Comment by busterb** [comment]
Sure, we can take it from here. Thanks for the contribution.

**Comment by feliwir** [comment]
Thanks!

**Comment by busterb** [comment]
According to the API docs, Windows Vista does not support BCRYPT_USE_SYSTEM_PREFERRED_RNG, but that is probably not a big blocker; I've been thinking of bumping past it anyway. Does it make sense to try updating this so that it is compatible with Vista.

**Comment by feliwir** [comment]
I understood it that it just ignores the flag on Vista, so it would still run.

**Comment by busterb** [comment]
Alright, seems that a related issue in OpenSSL https://github.com/openssl/openssl/issues/8644 reached the same conclusion.

**Comment by busterb** [comment]
I ran into some issues while testing: Vista is just as unstable as I remember, and this adds bcrypt.lib which needs some adjustments in the build process. Prepping a 3.0.0 release now, will consider this update for 3.0.1. Thanks!

**Comment by feliwir** [comment]
Alright, thanks. I thought bcrypt.lib is linked by default (because i had no issues calling that functions)

**Comment by sebres** [comment]
What's about dynamic linking with `bcrypt.dll` with a fallback to previous version (`wincrypt`) if bcrypt is not available (loadable)?
This way the same binary would be usable on old as well as on new windows versions.

**Comment by kinichiro** [comment]
https://github.com/libressl-portable/openbsd/commit/f3571756684921e2ea72f0eab9d99bcc5a58646b resolved this.
@feliwir can you close this ?

**Comment by feliwir** [comment]
Yes, thanks

**Pull request closed without merging**
