### PR TITLE
variable is used before initialization - bn_nist.c

### PR DESCRIPTION
**Pull request by kinichiro**
When macro bn_cp_32 is expanded to bn_cp_32_naked or bn_32_set_0 (line 389),
'to' variable seems not to set before use it.

HP C/aC++ compiler detects these warning.

"bn/bn_nist.c", line 611: warning #2549-D: variable "buf" is used before its
          value is set
        nist_set_224(buf.bn, c_d, 14, 13, 12, 11, 10, 9, 8);
                     ^

"bn/bn_nist.c", line 678: warning #2549-D: variable "t_d" is used before its
          value is set
                nist_set_224(t_d, buf.bn, 10, 9, 8, 7, 0, 0, 0);
                             ^

"bn/bn_nist.c", line 885: warning #2549-D: variable "t_d" is used before its
          value is set
                nist_set_256(t_d, buf.bn, 15, 14, 13, 12, 11, 0, 0, 0);
                             ^

"bn/bn_nist.c", line 887: warning #2549-D: variable "c_d" is used before its
          value is set
                nist_set_256(c_d, buf.bn, 0, 15, 14, 13, 12, 0, 0, 0);
                             ^

"bn/bn_nist.c", line 1139: warning #2549-D: variable "t_d" is used before its
          value is set
                nist_set_256(t_d, buf.bn, 0, 0, 0, 0, 0, 23 - 4, 22 - 4,

### CODE REVIEW

**Comment by bob-beck** [comment]
Kinichiro is this still an issue? We can't tell with the merge mess here ;)  if this is still an issue get us a clean diff please.

**Comment by bcook-r7** [comment]
the actual diff here is : https://github.com/libressl-portable/openbsd/pull/19/commits/60f4bc1b9aa2e9702865c41b41fa4f6357f8ced8

seems innocent enough, just initializing stack variables (famous last words :)

**Comment by kinichiro** [comment]
Yes, this still remains on HP-UX with HP C/aC++ compiler.

Only this compiler detects these warning, though, I appreciate if this is
fixed since this reduces unwanted warnings.

**Comment by bob-beck** [comment]
send it to tech@

**Comment by kinichiro** [comment]
I posted patch http://marc.info/?l=openbsd-tech&m=146849393023991&w=2

**Comment by busterb** [comment]
Applied, thanks a4a85843cc06fec26ee375c9754655aa4a4f850b a3e4c39e468ce618917b0cc7b4c8c0ae3309621c

**Comment by kinichiro** [comment]
Thanks a lot. It is good to resolve this.

**Pull request closed without merging**
