### PR TITLE
Add SM4 block cipher

### PR DESCRIPTION
**Pull request by dewyatt**
This adds the SM4 block cipher from the Chinese standard GB/T 32907-2016.

It's a port from OpenSSL (thanks @randombit!) with minimal changes to adapt to LibreSSL.

I confirmed that CI passes (with `LIBRESSL_GIT` and `OPENBSD_BRANCH` necessarily modified) and did some SM4 round-trip enc/dec testing between OpenSSL and LibreSSL.

This is a contribution from [Ribose Inc](https://www.ribose.com) (@riboseinc).

### CODE REVIEW

**Comment by dewyatt** [comment]
@botovq I've fixed the license issue, so this is now ready for an initial review when you have a moment.

cc @ronaldtse

**Comment by ronaldtse** [comment]
Thanks @dewyatt ! @bob-beck @botovq please feel free to let us know if there is anything to be changed. Appreciate it!

A clarifying note: this is a port of our contributed code to OpenSSL, not porting code that is already under the OpenSSL license.

**Comment by botovq** [comment]
This week-end we will land a slightly tweaked version of this patch in
OpenBSD and then sync this repo from there.

There is one question: Since it is a port of the code you ported to
OpenSSL in 2017, should the copyright in the license really say 2019?
Should that not rather be 2017 or possibly 2017, 2019?

**Comment by ronaldtse** [comment]
@botovq as you suggested, probably "2017, 2019" is most accurate. Would you mind if we change them now?

**Comment by botovq** [comment]
Thanks for the clarification. There is no need to update the
pull request. I'll change the date before committing to OpenBSD.

**Comment by ronaldtse** [comment]
Thank you @botovq ! 👍

**Comment by botovq** [comment]
This is now merged in OpenBSD.
The portable scaffold will be taken care of later.

**Comment by ronaldtse** [comment]
Thank you @botovq for the great news!

**Comment by dewyatt** [comment]
Sounds like we can close this. Thanks!

**Comment by ronaldtse** [comment]
Thanks @botovq and @dewyatt !!

**Pull request closed without merging**
