### PR TITLE
Cleanups, client certs and more

### PR DESCRIPTION
**Pull request by markokr**
Here is my cleaned up patch queue, for inital review mainly, altough I hope the easy stuff can be merged soon.

### CODE REVIEW

**Comment by markokr** [comment]
Could you update the git repo?  I can then regenerate patches on top of your current state.

**Comment by 4a6f656c** [comment]
The git repo should automatically update on a regular basis...

**Comment by bcook-r7** [comment]
I have not automated the process yet, since I typically have to ensure that the portable bits continue to build the latest openbsd code. We should be synced now though.

**Comment by bob-beck** [comment]
No it isn't.. brent or I have to run something on cvs :)

**Comment by bob-beck** [comment]
I'm wondering if we shouldn't just automate it anyway.. portable has enough
people following it that if we do
break something by a commit in base, they can assist in the effort of
keping portable building if we keep
head of tree daily-current.

(caveat a decent way technically to do this.. we can always discuss in
Croatia...)

**Comment by bob-beck** [comment]
I.E. brent, we should make the community help with the effort :)

**Comment by markokr** [comment]
Closing this, v2 is here: #42

**Pull request closed without merging**
