### PR TITLE
add callback variants of connect and accept.

### PR DESCRIPTION
**Pull request by krono**
- Use a (new) BIO for that

 - see https://github.com/libressl-portable/portable/issues/146

### CODE REVIEW

**Comment by bob-beck** [comment]
This looks interesting..  I think you should mail it to tech@openbsd.org and introduce yourself. ;)

**Comment by busterb** [comment]
I posted an updated patch to tech@openbsd.org. Going to close this PR since it was damaged due to the recent CVS tree reorganization.

**Comment by krono** [comment]
Thanks.

**Comment by bob-beck** [comment]
"damaged" by the recent tree reorg?   more like "obliterated" :)

**Comment by krono** [comment]
The perks of lettters-only-communication.
“Thank.” as in “Thank you for considering this and taking time to look. Much appreciated”. :)

**Comment by bob-beck** [comment]
Oh it's ok, I wasn't being upset.. I was laughing at how much the repo
changes mangle the PR's.  (as the guilty party behind much of the
reorganization)

anyway thank you very much for the diff.. it's being merged in now

**Comment by bob-beck** [comment]
BTW: been trying to get ahold of you outside of github.. If you can be
available Nov 2 for a week, mail me at beck@openbsd.org

**Pull request closed without merging**
