### PR TITLE
fix ENGINE_get_digest() doesn't work

### PR DESCRIPTION
**Pull request by nurse**
a35c259729689f7960598492bb39baf404b4abbd removes SHA-0 support.
But it causes to undef TEST_ENG_OPENSSL_SHA in eng_openssl.c.
A public API ENGINE_get_digest() is setuped by ENGINE_set_digests
called from bind_helper()<-engine_openssl()<-ENGINE_load_openssl(),
but it depends TEST_ENG_OPENSSL_SHA, which the commit breaks.

### CODE REVIEW

**Comment by busterb** [comment]
We had a similar discussion around what to do with 'openssl sha', which probably a non-zero population of programs assumed meant 'sha1', but really meant 'sha0'. It might be better that OpenSSL::Digest.new("SHA") fails explicitly than changes meaning.

**Comment by nurse** [comment]
@busterb Did you see the first one of ruby/openssl#40? I don't talk about it here.
I'm talking second one, which means the failure of `OpenSSL::Engine.by_id('openssl').digest("SHA1")`.
It is clearly careless miss of a35c259, which undefs TEST_ENG_OPENSSL_SHA and breaks ENGINE_set_digests(e, openssl_digests).

**Comment by busterb** [comment]
Ah, I see; thanks.

**Comment by busterb** [comment]
See d719654b1f04915cb31ecaf5b728a53138383bdc, cheers.

**Comment by nurse** [comment]
thanks!

**Pull request closed without merging**
